### ISSUE TITLE
AttributeError: 'ProGrad' object has no attribute 'prograd_backward_and_update'

### ISSUE THREAD

**Issue by wishx98** [BeierZhu/Prompt-align#11]
Hi, I encountered an AttributeError that I'm unable to resolve. Here's the specific error message I'm getting:

self.prograd_backward_and_update(xe_loss, kl_loss, self.cfg.LOSS.LAMBDA)
AttributeError: 'ProGrad' object has no attribute 'prograd_backward_and_update'

**Comment by BeierZhu** [comment]
Hi, Please first install our Dassl package

**Comment by wishx98** [comment]
Thanks for your help!
