### ISSUE TITLE
self.prograd_backward_and_update

### ISSUE THREAD

**Issue by SHIBOYA** [BeierZhu/Prompt-align#7]
I would like to express my appreciation for your excellent work.

While going through the code, I came across the method self.prograd_backward_and_update. Unfortunately, I wasn't able to find its specific definition. I believe this part is crucial for the overall understanding of your project, and I would greatly appreciate more insight into it.

Could you please point me to the file or code block where the self.prograd_backward_and_update method is defined? This would significantly aid my comprehension and utilization of your codebase.

**Comment by BeierZhu** [comment]
The function ``prograd_backwrad_and_update'' is in https://github.com/BeierZhu/Prompt-align/blob/main/Dassl.ProGrad.pytorch/dassl/engine/trainer.py
